AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ROLENAME:
    Type: String
    Description: Name of the role to assume in target accounts
  S3OUTPUTBUCKET:
    Type: String
    Description: S3 bucket for output CSV files
  S3OUTPUTPATH:
    Type: String
    Description: S3 path prefix for output CSV files
  SUBNETID:
    Type: String
    Description: Subnet ID for Lambda VPC configuration
  SECURITYGROUPID:
    Type: String
    Description: Security Group ID for Lambda VPC configuration
  PROXYHOST:
    Type: String
    Description: Hostname of the aws-proxy instance
  PROXYPORT:
    Type: String
    Description: Port of the aws-proxy instance
  LAYERVERSION:
    Type: String
    Description: Version number of the aws-proxy-cert layer

Resources:
  RDSMetricsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rds-scanner3
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 900
      MemorySize: 512
      Layers:
        - !Sub "arn:aws:lambda:us-east-1:552960913849:layer:aws-proxy-cert:${LAYERVERSION}"
      Environment:
        Variables:
          ROLE_NAME: !Ref ROLENAME
          S3_BUCKET: !Ref S3OUTPUTBUCKET
          S3_PATH: !Ref S3OUTPUTPATH
          HTTP_PROXY: !Sub "http://${PROXYHOST}:${PROXYPORT}"
          HTTPS_PROXY: !Sub "http://${PROXYHOST}:${PROXYPORT}"
          AWS_CA_BUNDLE: /opt/certs/aws-proxy.crt
          REQUESTS_CA_BUNDLE: /opt/certs/aws-proxy.crt
      VpcConfig:
        SecurityGroupIds:
          - !Ref SECURITYGROUPID
        SubnetIds:
          - !Ref SUBNETID
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Resource: '*'
            - Effect: Allow
              Action:
                - s3:PutObject
              Resource: !Sub 'arn:aws:s3:::${S3OUTPUTBUCKET}/${S3OUTPUTPATH}/*'
